### ISSUE TITLE
Bad request on POST login

### ISSUE THREAD

**Issue by juef17** [scarpentier/toutv-extra#13]
Program crashes when using the login option, because the GetResponse call at Login.cs line 72 results in a 400 error BAD request. However, looking up the token manually through my browser and copy/pasting it as a string in the code works perfectly:

`var token = "...my token here...";`

I'm not sure what's wrong with the request so forgive me if I can't provide a more direct solution.

Et merci beaucoup pour ce merveilleux outil, ça fait ma journée (et même plus)!

**Comment by scarpentier** [comment]
They might have changed the API. I'll have a look

Hehe merci :) Regarde [pytoutv](https://github.com/bvanheu/pytoutv) aussi c'est pas mal la même chose et bien plus robuste

**Comment by juef17** [comment]
Merci! :)

Et oui, j'ai bien vu pytoutv et ça marche effectivement numéro un! Et captvty fait la job aussi. Mais l'émission que je souhaitais télécharger nécessitait l'Extra, d'où le fait que tu es mon sauveur!
