### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by BarnoQC** [scarpentier/toutv-extra#3]
C:\Toutv>toutv fetch -m Le-retour-des-aventuriers-du-timbre-perdu

Executing fetch (Download a media):
    MediaUrl : Le-retour-des-aventuriers-du-timbre-perdu

Exception non gérée : System.ComponentModel.Win32Exception: Le fichier spécifié
est introuvable
   à System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startIn
fo)
   à System.Diagnostics.Process.Start()
   à toutv.Fetch.Run(String[] remainingArguments)
   à ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands
, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   à toutv.Program.Main(String[] args)

**Comment by scarpentier** [comment]
Bonjour @BarnoQC, merci pour le Issue.

Cette erreur est causée par l'absence de [ffmpeg](https://www.ffmpeg.org/) sur ton système, tel que spécifié dans le [readme](https://github.com/scarpentier/toutv-extra/blob/master/readme.md#requirements). Le dossier dans lequel `ffmpeg` réside doit être présent dans la variable d'environnement `PATH`.

Je conviens que je pourrais détecter l'absence de `ffmpeg` et afficher un message d'erreur plus convenable.

À l'avenir, merci de fournir un message plus descriptif et d'utiliser la syntaxe [Markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by BarnoQC** [comment]
Ok j'ai ffmpeg .

Comment je fais ou quoi j'écris comme syntaxe dans la fenêtre de commande 

Bruno Pitre
Envoyé de mon Iphone
Sur le réseau de TELUS
