### ISSUE TITLE
impossible to fetch

### ISSUE THREAD

**Issue by BarnoQC** [scarpentier/toutv-extra#5]
erreur 400 retourné par le serveur.
le fetching ne fonctionne plus

**Comment by BarnoQC** [comment]
Voici l'erreur en question quand on tente de refaire un login

Exception non gérée : System.Net.WebException: Le serveur distant a retourné une
 erreur : (400) Demande incorrecte.
   à System.Net.HttpWebRequest.GetResponse()
   à toutv.Login.Run(String[] remainingArguments)
   à ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands
, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   à toutv.Program.Main(String[] args)

**Comment by scarpentier** [comment]
Bonjour @BarnoQC. Quelle commande(s) avez-vous utilisé pour obtenir ce résultat?

**Comment by BarnoQC** [comment]
J'avais oublié de désactivé le VPN. Comme j'avais une adresse IP des US . le site bloquais le contenu.
