### ISSUE TITLE
Save stream as mp4 instead of MPEG-TS

### ISSUE THREAD

**Issue by scarpentier** [scarpentier/toutv-extra#6]
`MP4` is a superior container compared to `MPEGTS`.

**Comment by BarnoQC** [comment]
yes MP4 will be a better choice

**Comment by hence321** [comment]
Hi, nice tool you got here, when do you intend to change the container ?
Is there a way to choose the video quality prior to download?

I was using AdobeHDS.php script and the download is much faster....it saves in .FLV though, but really faster and top bitrate is chosen.

Is it possible to save the f4f fragments raw then merge them to be a single flv. the user could then convert the flv to however format he'd like?

Thank you anyway, this is really a nice script nonetheless
