### ISSUE TITLE
HTTP error 403 Forbidden

### ISSUE THREAD

**Issue by ocafebabe** [scarpentier/toutv-extra#8]
I always get that error when trying to download something:

toutv fetch -m les-pecheurs/S01E01

![toutv-ffmpeg](https://cloud.githubusercontent.com/assets/3409735/9215646/66c08a10-407b-11e5-9e22-2db74aa568d9.PNG)

**Comment by scarpentier** [comment]
Most likely your token got invalidated by logging somewhere else between your `login` and `fetch` command
