### ISSUE TITLE
Problème à télécharger outlander

### ISSUE THREAD

**Issue by redalastor** [scarpentier/toutv-extra#9]
La commande `fetch -m outlander/S01E01` termine silencieusement sans rien télécharger. En mode `batch`, on constate le même problème avec tous les épisodes sauf le neuvième de la première saison.

J'ai essayé une autre série (série noire) et je n'ai pas eu ce problème.

**Comment by scarpentier** [comment]
Les émissions qui ne sont disponibles qu'à travers le service Extra (comme Outlander) ne disposent pas du même API et je n'ai malheureusement trouvé aucune façon légale de contourner l'encryption de ces flux.
